### Numpy

## Numpy is a f undamental library mainly for scientific operatins. It provide support of array and matrics along with a collection of mathematical operations

In [1]:
!pip install numpy 

In [2]:
import numpy as np

In [5]:
## create 1d array
arr1=np.array([1,2,3,4,5])
arr1 
print(type(arr1))
print(arr1.shape)

<class 'numpy.ndarray'>
(5,)


In [11]:
arr2=np.array([1,2,3,4,5])
print(arr2)
arr2.reshape(1,5)  # 1 rows and 5 columns
print(arr2)
print(arr1.shape)

[1 2 3 4 5]
[1 2 3 4 5]
(5,)


In [12]:
arr2=np.array([[1,2,3,4,5],[5,6,7,8,9]])
arr2.shape

(2, 5)

In [16]:
## Custom array by inputing rannge
arr = np.arange(0,10,2).reshape(5,1)
arr

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
## Identity matrix
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
## Attributes of Numpy Array

arr=np.array([[1,2,3],[4,5,6]])

print("Array \n",arr)
print("Shape:",arr.shape)
print("Number of Dimensions:",arr.ndim)
print("Size(Number of elements):",arr.size)
print("Data Types",arr.dtype)
print("Item size in Bytes",arr.itemsize)

Array 
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimensions: 2
Size(Number of elements): 6
Data Types int64
Item size in Bytes 8


In [25]:
## Numpy vectorized operatiosn
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Elemenst wise addition
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1//arr2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[0 0 0 0 0]


In [26]:
## Universal Funtions
arr=np.array([1,2,3,4,5])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [47]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)



Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
# print(arr[0:3:,1:3])
# print(arr[0][0])
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [48]:
## Modify arr elements
arr[0][0]=109
arr[1:]=100
# arr[1:,2:]=100
arr

array([[109,   2,   3,   4],
       [  5,   6, 100, 100],
       [  9,  10, 100, 100]])

In [49]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)
median=np.median(data)
cariance=np.var(data)
# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [50]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])