In [2]:
import numpy as np

In [5]:
org_array=np.random.randint(1,21,size=(5,5))
print(org_array)

org_array[0:,2:3]=1
print(org_array)


[[13  4  6 16 10]
 [ 9 20  5  3  6]
 [ 3  4  6  8  6]
 [12 11  1 19 18]
 [19 20 18 17  7]]
[[13  4  1 16 10]
 [ 9 20  1  3  6]
 [ 3  4  1  8  6]
 [12 11  1 19 18]
 [19 20  1 17  7]]


In [ ]:
array=np.random.randint(1,16,size=(4,4))
print(array)


np.fill_diagonal(array, 0)
print(array)

[[14  8 11  8]
 [13  1  7  6]
 [ 9 14  1 10]
 [14 10  2  9]]
[[ 0  8 11  8]
 [13  0  7  6]
 [ 9 14  0 10]
 [14 10  2  0]]


In [ ]:
array=np.random.randint(1,37,size=(6,6))
print(array)
new_array=array[2:5,1:4]
print(new_array)

[[17 11 14 29 23 16]
 [22 21 36 17 36 14]
 [31 31 20  3 32 24]
 [20  1  6  7 30 21]
 [20 34 34 36 11  6]
 [19 18 35 31 33  6]]
[[ 6  7 30]
 [34 36 11]
 [35 31 33]]


In [10]:
#2. Create a NumPy array of shape (5, 5) with random integers.
#  Extract the elements on the border.

array=np.random.randint(1,37,size=(5,5))
print(array)

# Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

[[34  7  8 25 34]
 [22 16 15  2 32]
 [13 29 10 11 36]
 [21 21 19 25  4]
 [30  5  7 15 30]]
Border elements:
[34  7  8 25 34 30  5  7 15 30 22 13 21 32 36  4]


In [11]:
 # ### Assignment 3: Array Operations

# 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise 
# addition, subtraction, multiplication, and division.


array1=np.random.randint(1,37,size=(3,4))
array2=np.random.randint(1,37,size=(3,4))

sum_Array=array1+array2
print(sum_Array)

[[37 43 35 50]
 [53 40 36 29]
 [31 51 35 56]]


In [6]:
array=np.random.randint(1,11,size=(5,5))
print(array)

mean=np.mean(array)
print("mean",mean)
median=np.median(array)
print("medain",median)
std=np.std(array)
print("std",std)
var=np.var(array)
print("var",var)


[[ 3 10  5  1 10]
 [ 2  5  5  7  7]
 [ 5  6  5  7  2]
 [10  3  2 10  6]
 [ 2  9  2  5  4]]
mean 5.32
medain 5.0
std 2.810266891240047
var 7.897599999999999


In [10]:
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)
result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[4 4 4]
 [4 1 5]
 [8 4 7]]
1D array:
[1 8 1]
Resulting array:
[[ 5 12  5]
 [ 5  9  6]
 [ 9 12  8]]


In [11]:
array = np.random.randint(1, 11, size=(4, 4))
col_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(col_array)

result=array-col_array[:,np.newaxis]
print(result)

Original array:
[[10  4  9  8]
 [ 8  8  8  7]
 [ 5  9 10  2]
 [ 5  7  7  8]]
1D array:
[8 7 1 2]
[[ 2 -4  1  0]
 [ 1  1  1  0]
 [ 4  8  9  1]
 [ 3  5  5  6]]


In [12]:
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

Original matrix:
[[1 5 6]
 [7 6 9]
 [3 2 1]]
Determinant: 64.00000000000003
Inverse:
[[-0.1875    0.109375  0.140625]
 [ 0.3125   -0.265625  0.515625]
 [-0.0625    0.203125 -0.453125]]
Eigenvalues: [12.88631031 -3.4444025  -1.44190781]


In [13]:
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform matrix multiplication
result = np.dot(array1, array2)
print("Matrix multiplication result:")
print(result)

Array 1:
[[ 1  9  7]
 [ 8 10  4]]
Array 2:
[[1 9]
 [3 3]
 [2 9]]
Matrix multiplication result:
[[ 42  99]
 [ 46 138]]


In [14]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Reshape the array to shape (1, 9)
reshaped_array_1 = array.reshape((1, 9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

# Reshape the array to shape (9, 1)
reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [19]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Flatten the array
# flattened_array = array.flatten()
flattened_array = array.reshape(25,1)
print("Flattened array:")
# print(flattened_array)

# Reshape the array back to (5, 5)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

Original array:
[[19 11 16 11 12]
 [ 2  9 20 18 11]
 [20  4 10 13 13]
 [11  3 12  1  4]
 [ 6 20 16 12 10]]
Flattened array:
Reshaped array:
[[19 11 16 11 12]
 [ 2  9 20 18 11]
 [20  4 10 13 13]
 [11  3 12  1  4]
 [ 6 20 16 12 10]]


In [20]:
array = np.random.randint(1, 21, size=(4, 4))
print(array)
array[array > 7] = 7
print(array)

[[16 18 13  5]
 [ 4  8 11  5]
 [ 6 12  6  1]
 [19  3  2 16]]
[[7 7 7 5]
 [4 7 7 5]
 [6 7 6 1]
 [7 3 2 7]]


In [25]:
array = np.array(
    [('Pankaj', 34), ('Deepak', 67)],
    dtype=[('name', 'U10'), ('age', 'i4')]
)

sorted_array = np.sort(array, order='age')
print(sorted_array)

[('Pankaj', 34) ('Deepak', 67)]
